branches:
  except:
  - /.*(.tmp)$/

language: rust
matrix:
  include:
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly

sudo: false
script:
  - cargo test --all

notifications:
  email:
    on_success: never
