[package]
name = "easy-jsonrpc"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
jsonrpc_proc_macro = { path = "./proc_macros" }
serde_json = "1"
serde = "1"
jsonrpc-core = "10.0.1"

[dev-dependencies]
assert_matches = "1.3.0"
